export enum ActionType {
  FETCH_GAMES_START = 'FETCH_GAMES_START',
  FETCH_GAMES_SUCCESSS = 'FETCH_GAMES_SUCCESS',
  FETCH_GAMES_ERROR = 'FETCH_GAMES_ERROR',

  FETCH_BETS_HISTORY_START = 'FETCH_BETS_HISTORY_START',
  FETCH_BETS_HISTORY_SUCCESSS = 'FETCH_BETS_HISTORY_SUCCESS',
  FETCH_BETS_HISTORY_ERROR = 'FETCH_BETS_HISTORY_ERROR',

  GET_BUTTON_STATE_START = 'GET_BUTTON_STATE_START',
  GET_BUTTON_STATE_SUCCESS = 'GET_BUTTON_STATE_SUCCESS',
  GET_BUTTON_STATE_ERROR = 'GET_BUTTON_STATE_ERROR',

  ADD_BET_SLIP = 'ADD_BET_SLIP',
  REMOVE_BET_SLIP = 'REMOVE_BET_SLIP',

  UPDATE_ODDS_FORMAT = 'UPDATE_ODDS_FORMAT',
}
